✖ 1 HW2_FINAL ❯❯❯ python adversarial_finetune.py                                                                     (tf2)

2020-11-24 20:50:30.790889: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-11-24 20:50:30.790926: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do nothave a GPU set up on your machine.
2020-11-24 20:50:31.928732: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-11-24 20:50:31.932912: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-24 20:50:31.933620: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.73GiB deviceMemoryBandwidth: 573.69GiB/s
2020-11-24 20:50:31.933726: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-11-24 20:50:31.933840: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory
2020-11-24 20:50:31.933993: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2020-11-24 20:50:31.934088: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2020-11-24 20:50:31.934198: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory
2020-11-24 20:50:31.934279: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory
2020-11-24 20:50:31.940048: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-11-24 20:50:31.940063: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-11-24 20:50:31.940358: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-24 20:50:31.965801: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3199980000 Hz
2020-11-24 20:50:31.968197: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5601fde80130 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-24 20:50:31.968269: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-11-24 20:50:31.973679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-24 20:50:31.973690: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]

Loading new pretrained sepreresnet56_cifar10 model
Initial evaluation
(Test Accuracy) With autoencoder protection:
  Regular: 0.9532 --> 0.8121
  FGSM: 0.4652 --> 0.7367
  PGD: 0.045 --> 0.7614
(0) LR: 0.0001, BS: 256, EPOCHS: 1, AE outputs + original adversarial examples
1172/1172 [==============================] - 2335s 2s/step - loss: 1.6044
(Test Accuracy) With autoencoder protection:
  Regular: 0.9072 --> 0.8467
  FGSM: 0.6954 --> 0.7973
  PGD: 0.5616 --> 0.8132
WARNING:tensorflow:From /home2/john_gilbert/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/training/tracking/tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:From /home2/john_gilbert/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/training/tracking/tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in afuture version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
2020-11-24 21:33:24.100962: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
(1) LR: 0.0001, BS: 256, EPOCHS: 2, AE outputs + original adversarial examples
Epoch 1/2
1172/1172 [==============================] - 2331s 2s/step - loss: 1.0615
Epoch 2/2
1172/1172 [==============================] - 2332s 2s/step - loss: 0.8657
(Test Accuracy) With autoencoder protection:
  Regular: 0.9015 --> 0.8418
  FGSM: 0.731 --> 0.7988
  PGD: 0.6821 --> 0.8165
(2) LR: 0.0001, BS: 256, EPOCHS: 1, just AE outputs
782/782 [==============================] - 1554s 2s/step - loss: 0.5267
(Test Accuracy) With autoencoder protection:
  Regular: 0.9008 --> 0.8483
  FGSM: 0.712 --> 0.81
  PGD: 0.6171 --> 0.8253
Saving model to model/robust_model
(3) LR: 1e-05, BS: 256, EPOCHS: 3, just AE outputs
Epoch 1/3
782/782 [==============================] - 1553s 2s/step - loss: 0.4377
Epoch 2/3
782/782 [==============================] - 1553s 2s/step - loss: 0.4037
Epoch 3/3
782/782 [==============================] - 1555s 2s/step - loss: 0.3864
(Test Accuracy) With autoencoder protection:
  Regular: 0.9159 --> 0.8715
  FGSM: 0.7191 --> 0.8266
  PGD: 0.6157 --> 0.8447
Saving model to model/robust_model
[I] The last command took 13904.456 seconds.